### ISSUE TITLE
Snipe brush leaves black lighting spots.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/fastasyncvoxelsniper#5]
Paper dev 273 (Spigot 1.15.2)
FAWE dev 217
FAVS dev 14

FAWE Config
https://paste.ubuntu.com/p/5w2yRsq7S6/
VoxelSniper Config
https://paste.ubuntu.com/p/k8b9qB2cc5/

* ``/b s``
* ``/b 1``
* ``/v air``

When you snipe a block with the arrow, it leaves the removed block with black lighting.

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: true
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 2
  # If existing lighting should be removed before relighting
  remove-first: true
```

Also tested with

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: false
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 1
  # If existing lighting should be removed before relighting
  remove-first: false
```
